def printScreen(caseList, moneyList,name,userCase):
    print()
    print('-----------------------------------------------------')
    print(' Cases                         | Values    ')
    print('-----------------------------------------------------')
    print('                               | '+moneyList[0]+'  '+moneyList[13]+' ')
    print('  '+caseList[20].face+'   '+caseList[21].face+'   '+caseList[22].face+'   '+caseList[23].face+'   '+caseList[24].face+'   '+caseList[25].face+'  | '+moneyList[1]+'  '+moneyList[14]+' ')
    print('                               | '+moneyList[2]+'  '+moneyList[15]+' ')
    print('  '+caseList[13].face+'  '+caseList[14].face+'  '+caseList[15].face+'  '+caseList[16].face+'  '+caseList[17].face+'  '+caseList[18].face+'  '+caseList[19].face+'   | '+moneyList[3]+'  '+moneyList[16]+' ')
    print('                               | '+moneyList[4]+'  '+moneyList[17]+' ')
    print('  '+caseList[6].face+'   '+caseList[7].face+'   '+caseList[8].face+'   '+caseList[9].face+'   '+caseList[10].face+'   '+caseList[11].face+'  '+caseList[12].face+' | '+moneyList[5]+'  '+moneyList[18]+' ')
    print('                               | '+moneyList[6]+'  '+moneyList[19]+' ')
    print('   '+caseList[0].face+'   '+caseList[1].face+'   '+caseList[2].face+'   '+caseList[3].face+'   '+caseList[4].face+'   '+caseList[5].face+'       | '+moneyList[7]+'  '+moneyList[20]+' ')
    print('                               | '+moneyList[8]+'  '+moneyList[21]+' ')
    print('-------------------------------| '+moneyList[9]+'  '+moneyList[22]+' ')
    print('  '+name+',                        | '+moneyList[10]+'  '+moneyList[23]+' ')
    print('       Your Case: '+userCase+'           | '+moneyList[11]+'  '+moneyList[24]+' ')
    print('                               | '+moneyList[12]+'  '+moneyList[25]+' ')
    print('-----------------------------------------------------')
    print()